artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_path: Experiments\Kaggle_Training_Dataset_v2.csv
  #local_data_file: artifacts/data_ingestion/data.zip
  local_file_dir: artifacts/data_ingestion/data.csv