artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  file_key: Customer_Segmentation/segmentation data.csv
  download_path: artifacts/data_ingestion/data.csv
  #local_file_dir: artifacts/data_ingestion/data.csv