artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  file_key: Customer_Segmentation/segmentation data.csv
  download_path: artifacts/data_ingestion/data.csv
  #local_file_dir: artifacts/data_ingestion/data.csv
data_validation:
  root_dir: artifacts/data_validation
  target_file : artifacts/data_ingestion/data.csv
  result_path: artifacts/data_validation/result.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv

model_training:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_transformation/final_data.csv
  #test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

  
